# Generated by Django 3.1.2 on 2021-12-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, verbose_name='DNI')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('birthDate', models.DateField(verbose_name='Birthday')),
                ('registerDate', models.DateField(verbose_name='Date of register')),
                ('active', models.BooleanField(verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, verbose_name='DNI')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('biography', models.TextField(max_length=260, verbose_name='Biography')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50, verbose_name='Name')),
                ('password', models.CharField(max_length=18, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=260, verbose_name='Description')),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.category', verbose_name='IdCategory')),
                ('idEmployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.employees', verbose_name='IdEmployee')),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationDate', models.DateField(verbose_name='Registration Date')),
                ('rol', models.TextField(max_length=260, verbose_name='Rol')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.client', verbose_name='IdClient')),
                ('idProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.project', verbose_name='IdProject')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.user', verbose_name='IdUser'),
        ),
        migrations.AddField(
            model_name='client',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.user', verbose_name='IdUser'),
        ),
    ]
