# Generated by Django 3.1.2 on 2021-12-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registerDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of register'),
        ),
    ]
