# Generated by Django 3.1.2 on 2022-01-04 19:34

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birthday'),
        ),
    ]
