# Generated by Django 3.1.2 on 2021-12-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_auto_20211223_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='username',
        ),
    ]
