# Generated by Django 3.1.2 on 2022-01-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20220104_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=9, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_user',
            field=models.CharField(max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Surname'),
        ),
    ]
