# Generated by Django 3.1.2 on 2021-12-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_auto_20211223_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.BooleanField(null=True, verbose_name='Active'),
        ),
    ]
